#! /bin/bash

# checking whether OMERO is running
omero login -s localhost -u suguru -w omx > /dev/null 2> /dev/null
if [ "$?" -ne 0 ]; then
    su -c "omero admin start" pcarlton
    omero login -s localhost -u suguru -w omx > /dev/null 2> /dev/null
    if [ $? -ne 0 ]; then
        echo '[ERROR] OMERO.server is not running.'
        exit 1
    fi
fi
omero logout

# checking whether /data2 is mounted
mounts=`grep /data2 /proc/mounts`
if [ -z "$mounts" ]; then
    echo '[ERROR] /data2 is not mounted.'
    exit 2
fi

running_file='/tmp/omero_importer_is_running'

if [ -e $running_file ];then
    echo '[ERROR] OMERO importer is already running!'
    exit 3
fi

touch $running_file

python omero_importer.py $@

rm $running_file
